const vehicles = [
{
  id: "2015-bmw-x5-xdrive30d-black",
  title: "2015 BMW X5 xDrive30d F15 Auto 4x4",
  price: 20888,
  kms: "160,605 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Azurite Black",
  engine: "3.0L 6 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGBMWF15X57SEAT",
  imageLabel: "BMW X5",
  image: "assets/vehicles/BMW X5 2015 Black/car_01.png",
  images: [
    "assets/vehicles/BMW X5 2015 Black/car_01.png",
    "assets/vehicles/BMW X5 2015 Black/car_02.png",
    "assets/vehicles/BMW X5 2015 Black/car_03.png",
    "assets/vehicles/BMW X5 2015 Black/car_04.png",
    "assets/vehicles/BMW X5 2015 Black/car_05.png",
    "assets/vehicles/BMW X5 2015 Black/car_06.png",
    "assets/vehicles/BMW X5 2015 Black/car_07.png",
    "assets/vehicles/BMW X5 2015 Black/car_08.png",
    "assets/vehicles/BMW X5 2015 Black/car_09.png",
    "assets/vehicles/BMW X5 2015 Black/car_10.png",
    "assets/vehicles/BMW X5 2015 Black/car_11.png",
    "assets/vehicles/BMW X5 2015 Black/car_12.png",
    "assets/vehicles/BMW X5 2015 Black/car_13.png",
    "assets/vehicles/BMW X5 2015 Black/car_14.png",
    "assets/vehicles/BMW X5 2015 Black/car_15.png",
    "assets/vehicles/BMW X5 2015 Black/car_16.png",
    "assets/vehicles/BMW X5 2015 Black/car_17.png",
    "assets/vehicles/BMW X5 2015 Black/car_18.png",
    "assets/vehicles/BMW X5 2015 Black/car_19.png",
    "assets/vehicles/BMW X5 2015 Black/car_20.png",
    "assets/vehicles/BMW X5 2015 Black/car_21.png",
    "assets/vehicles/BMW X5 2015 Black/car_22.png",
    "assets/vehicles/BMW X5 2015 Black/car_23.png",
    "assets/vehicles/BMW X5 2015 Black/car_24.png",
    "assets/vehicles/BMW X5 2015 Black/car_25.png",
    "assets/vehicles/BMW X5 2015 Black/car_26.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x5-2015/oag-ad-25819559/",
  description: "2015 BMW X5 xDrive30d F15 Auto 4x4 finished in Azurite Black with black interior. A highly optioned luxury SUV offering powerful turbo diesel performance, premium comfort and strong practicality. Powered by a 3.0L 6-cylinder turbo diesel engine paired with an 8-speed sports automatic transmission and BMW xDrive all-wheel drive. This X5 has travelled 156,605km and is listed with roadworthy certificate provided, finance available and 12 month warranty included.",
  features: [
    "7 seat configuration",
    "Full leather interior",
    "Electric memory seats",
    "Panoramic sunroof",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "360 degree camera",
    "Adaptive cruise control",
    "Lane departure warning",
    "Blind spot monitoring",
    "Forward collision warning",
    "AEB low speed",
    "Dual-zone climate control",
    "Power tailgate",
    "Keyless entry",
    "Push-button start",
    "Premium sound system",
    "9 speaker stereo",
    "DVD player",
    "USB input",
    "AUX input",
    "iPod input",
    "Head-up display",
    "Voice recognition",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Heated mirrors",
    "19-inch alloy wheels",
    "Roof rails",
    "Selectable driving modes",
    "Stop-start system",
    "Sports steering wheel",
    "Hill descent control",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Tyre pressure monitoring",
    "6 airbags"
  ]
},
{
  id: "2016-bmw-2-series-228i-sport-line",
  title: "2016 BMW 2 Series 228i Sport Line F22 Auto",
  price: 19000,
  kms: "94,880 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "Coupe",
  colour: "White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOBMW2",
  imageLabel: "BMW 2 Series",
  image: "assets/vehicles/BMW 2 Series 2016/car_01.png",
  images: [
    "assets/vehicles/BMW 2 Series 2016/car_02.png",
    "assets/vehicles/BMW 2 Series 2016/car_01.png",
    "assets/vehicles/BMW 2 Series 2016/car_03.png",
    "assets/vehicles/BMW 2 Series 2016/car_04.png",
    "assets/vehicles/BMW 2 Series 2016/car_05.png",
    "assets/vehicles/BMW 2 Series 2016/car_06.png",
    "assets/vehicles/BMW 2 Series 2016/car_07.png",
    "assets/vehicles/BMW 2 Series 2016/car_08.png",
    "assets/vehicles/BMW 2 Series 2016/car_09.png",
    "assets/vehicles/BMW 2 Series 2016/car_10.png",
    "assets/vehicles/BMW 2 Series 2016/car_11.png",
    "assets/vehicles/BMW 2 Series 2016/car_12.png",
    "assets/vehicles/BMW 2 Series 2016/car_13.png",
    "assets/vehicles/BMW 2 Series 2016/car_14.png",
    "assets/vehicles/BMW 2 Series 2016/car_15.png",
    "assets/vehicles/BMW 2 Series 2016/car_16.png",
    "assets/vehicles/BMW 2 Series 2016/car_17.png",
    "assets/vehicles/BMW 2 Series 2016/car_18.png",
    "assets/vehicles/BMW 2 Series 2016/car_19.png",
    "assets/vehicles/BMW 2 Series 2016/car_20.png",
    "assets/vehicles/BMW 2 Series 2016/car_21.png",
    "assets/vehicles/BMW 2 Series 2016/car_22.png",
    "assets/vehicles/BMW 2 Series 2016/car_23.png",
    "assets/vehicles/BMW 2 Series 2016/car_24.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-2-series-2016/oag-ad-25897808/",
  description: "2016 BMW 2 Series 228i Sport Line F22 Auto finished in white with a stylish coupe body. A sporty and refined 2-door BMW coupe offering strong turbo petrol performance, premium comfort and everyday usability. Powered by a 2.0L turbo intercooled 4-cylinder petrol engine paired with an 8-speed sports automatic transmission and rear-wheel drive. This BMW 228i has travelled 94,880km and is listed with 12 month warranty included.",
  features: [
    "Bluetooth",
    "Reverse camera",
    "GPS satellite navigation",
    "Front parking sensors",
    "Rear parking sensors",
    "Cruise control",
    "Automatic headlights",
    "Bi-xenon headlights",
    "LED daytime running lights",
    "Front fog lamps",
    "Rear fog lamps",
    "Dual-zone climate control",
    "Leather interior",
    "Sports front seats",
    "Push-button start",
    "Digital radio",
    "USB input",
    "AUX input",
    "iPod input",
    "MP3 decoder",
    "Inbuilt harddisk drive",
    "6 speaker stereo",
    "Multi-function control screen",
    "Smart device app display/control",
    "Paddle shifters",
    "Selectable driving modes",
    "Sports steering wheel",
    "Electric power steering",
    "Rain-sensing wipers",
    "Heated washer jets",
    "Electric heated mirrors",
    "Trip computer",
    "On-board computer",
    "Tyre pressure monitoring",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Rear wheel drive",
    "Stop-start system",
    "ABS brakes",
    "Brake assist",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "6 airbags"
  ]
},
{
  id: "2012-volkswagen-tiguan-132tsi-pacific",
  title: "2012 Volkswagen Tiguan 132TSI Pacific 5N Auto 4MOTION MY12.5",
  price: 7342,
  kms: "202,000 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Candy White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGTIGUANTSI",
  imageLabel: "Volkswagen Tiguan",
  image: "assets/vehicles/Volkswagen Tiguan 2012/car_01.png",
  images: [
    "assets/vehicles/Volkswagen Tiguan 2012/car_01.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_02.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_03.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_04.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_05.png",
    "assets/vehicles/Volkswagen Tiguan 2012/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/volkswagen-tiguan-2012/oag-ad-26014328/",
  description: "2012 Volkswagen Tiguan 132TSI Pacific 5N Auto 4MOTION MY12.5 finished in Candy White with grey interior. A practical and comfortable compact SUV with all-wheel drive capability, useful family space and strong Volkswagen safety features. Powered by a 2.0L turbo intercooled 4-cylinder petrol engine paired with a 6-speed automatic transmission and 4MOTION all-wheel drive. Features include Bluetooth, front and rear parking sensors, cruise control, automatic headlights, dual-zone climate control, rear air conditioning, 8-speaker stereo, AUX/USB input, power windows, rain-sensing wipers, electric heated mirrors, roof rails, multi-function steering wheel, electric park brake, hill holder, traction control and electronic stability control. This Tiguan has travelled 202,000km and is listed as drive away, with 12 month warranty included.",
  features: [
    "Bluetooth",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Automatic headlights",
    "Dual-zone climate control",
    "Rear air conditioning",
    "8 speaker stereo",
    "AUX input",
    "USB input",
    "MP3 decoder",
    "CD player",
    "Power windows",
    "Rain-sensing wipers",
    "Rear wiper",
    "Electric heated mirrors",
    "Remote central locking",
    "Engine immobiliser",
    "Multi-function steering wheel",
    "Trip computer",
    "Cloth interior",
    "Split fold rear seats",
    "Rear sliding seat adjustment",
    "Roof rails",
    "16-inch alloy wheels",
    "Electric park brake",
    "Hill holder",
    "Electronic differential lock",
    "4MOTION all-wheel drive",
    "Traction control",
    "Electronic stability control",
    "Rollover stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2017-mercedes-benz-gla220d",
  title: "2017 Mercedes-Benz GLA-Class GLA220 d Auto",
  price: 17000,
  kms: "125,349 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Cirrus White",
  engine: "2.1L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "ADFGADSF",
  imageLabel: "Mercedes-Benz GLA",
  image: "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
  images: [
    "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_02.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_03.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mercedes-benz-gla-class-2017/oag-ad-26016339/",
  description: "2017 Mercedes-Benz GLA220 d X156 Auto finished in Cirrus White with black interior. A premium compact luxury SUV offering strong turbo diesel efficiency, smooth automatic driving and a refined Mercedes-Benz cabin. Powered by a 2.1L turbo diesel 4-cylinder engine paired with a 7-speed sports automatic dual clutch transmission. Features include Apple CarPlay, Android Auto, satellite navigation, reverse camera, front and rear parking sensors, blind spot monitoring, autonomous emergency braking, dual-zone climate control, leather-look interior, heated front seats, electric front seats, keyless start, power tailgate, automatic bi-xenon headlights, rain-sensing wipers, Bluetooth, digital radio, 18-inch alloy wheels and excellent fuel economy. This GLA220 d has travelled 125,349km and is listed with roadworthy certificate, registration, finance available and 12 month premium warranty included.",
  features: [
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Automated parking assistance",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Driver attention detection",
    "Cruise control",
    "Speed limiter",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Leather-look interior",
    "Heated front seats",
    "Electric front seats",
    "Electric lumbar support",
    "Keyless start",
    "Push-button start",
    "Power tailgate",
    "Digital radio",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "CD player",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Tyre pressure monitoring",
    "Roof rails",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Electric park brake",
    "Hill holder",
    "Stop-start system",
    "Selectable driving modes",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "9 airbags"
  ]
},
{
  id: "2017-land-rover-discovery-sport-sd4-hse",
  title: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18",
  price: 15999,
  kms: "93,780 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "JHGSDF2225",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Sport 2017/car_01.png",
  images: [
    "assets/vehicles/Range Rover Sport 2017/car_01.png",
    "assets/vehicles/Range Rover Sport 2017/car_02.png",
    "assets/vehicles/Range Rover Sport 2017/car_03.png",
    "assets/vehicles/Range Rover Sport 2017/car_04.png",
    "assets/vehicles/Range Rover Sport 2017/car_05.png",
    "assets/vehicles/Range Rover Sport 2017/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2017/oag-ad-26015662/",
  description: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18 finished in Fuji White with black interior. A premium family SUV combining luxury comfort, strong twin turbo diesel performance and intelligent all-wheel drive capability. Powered by a 2.0L twin turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission. Features include full leather interior, panoramic glass sunroof, satellite navigation, Apple CarPlay, Android Auto, reverse camera, front and rear parking sensors, electric tailgate, heated front seats, electric front seats with memory, keyless entry, push-button start, dual-zone climate control, Meridian premium sound system, lane keep assist, blind spot monitoring, autonomous emergency braking, adaptive cruise control and 19-inch alloy wheels. This Discovery Sport has travelled only 86,408km and is listed as drive away with roadworthy certificate, registration included, finance available and 12 month premium warranty included.",
  features: [
    "Full leather interior",
    "Panoramic glass sunroof",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Lane departure warning",
    "Lane keep assist",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Adaptive cruise control",
    "Keyless entry",
    "Push-button start",
    "Electric tailgate",
    "Heated front seats",
    "Ventilated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Passenger memory seat",
    "Electric lumbar support",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Meridian premium sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "Memory card reader",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Speed limiter",
    "Automatic headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Ambient interior lighting",
    "Split fold rear seats",
    "Sliding rear seat adjustment",
    "Cargo cover",
    "ISOFIX child seat anchors",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 on demand",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2021-land-rover-discovery-sport-p200-r-dynamic-s",
  title: "2021 Land Rover Discovery Sport P200 R-Dynamic S Auto 4x4 MY21",
  price: 27140,
  kms: "106,147 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "HGJF22254",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Discovery 2021/car_01.png",
  images: [
    "assets/vehicles/Range Rover Discovery 2021/car_01.png",
    "assets/vehicles/Range Rover Discovery 2021/car_02.png",
    "assets/vehicles/Range Rover Discovery 2021/car_03.png",
    "assets/vehicles/Range Rover Discovery 2021/car_04.png",
    "assets/vehicles/Range Rover Discovery 2021/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2021/oag-ad-26015523/",
  description: "2021 Land Rover Discovery Sport P200 R-Dynamic S Auto 4x4 MY21 finished in Fuji White with black interior. A late-model premium SUV with modern R-Dynamic styling, 7-seat practicality, strong turbo petrol performance and advanced safety technology. Powered by a 2.0L turbo petrol 4-cylinder engine paired with a 9-speed sports automatic transmission and constant 4x4 drive. Features include Apple CarPlay, Android Auto, satellite navigation, 360 degree camera, front and rear parking sensors, blind spot assist, lane keep assist, autonomous emergency braking, adaptive cruise control, keyless start, electric tailgate, dual-zone climate control, leather-look interior, electric front seats, digital driver display, LED headlights, rain-sensing wipers, 18-inch alloy wheels and 5 star ANCAP safety rating. This Discovery Sport has travelled 106,147km and is listed with roadworthy certificate, registration included, finance available and 12 month premium warranty included.",
  features: [
    "7 seats",
    "R-Dynamic sports styling package",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "360 degree camera",
    "Reverse camera",
    "Front camera",
    "Side cameras",
    "Front parking sensors",
    "Rear parking sensors",
    "Rear cross traffic alert",
    "Blind spot assist",
    "Lane departure warning",
    "Lane keep assist",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Adaptive cruise control",
    "Driver fatigue warning",
    "Road sign recognition",
    "Keyless start",
    "Push-button start",
    "Electric tailgate",
    "Dual-zone climate control",
    "Pollen filter",
    "Leather-look interior",
    "Partial leather seats",
    "Electric front seats",
    "Electric lumbar support",
    "Digital driver display",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Wireless hotspot",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Speed limiter",
    "Ambient lighting",
    "Footwell lamps",
    "Automatic LED headlights",
    "LED daytime running lights",
    "LED tail lights",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Power windows",
    "ISOFIX child seat anchors",
    "Cargo cover",
    "Cargo tie down hooks",
    "18-inch alloy wheels",
    "Space saver spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 constant drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2015-kia-sorento-platinum-awd",
  title: "2015 Kia Sorento Platinum Auto AWD MY15",
  price: 17762,
  kms: "123,604 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Sunset Red",
  engine: "2.2L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGKIASORENTO",
  imageLabel: "Kia Sorento",
  image: "assets/vehicles/KIA Sorrento 2015/car_01.png",
  images: [
    "assets/vehicles/KIA Sorrento 2015/car_01.png",
    "assets/vehicles/KIA Sorrento 2015/car_02.png",
    "assets/vehicles/KIA Sorrento 2015/car_03.png",
    "assets/vehicles/KIA Sorrento 2015/car_04.png",
    "assets/vehicles/KIA Sorrento 2015/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/kia-sorento-2015/oag-ad-25964146/",
  description: "2015 Kia Sorento Platinum Auto AWD MY15 finished in Sunset Red with black interior. A top-of-the-range 7-seat family SUV offering strong turbo diesel performance, excellent practicality and premium comfort features. Powered by a 2.2L turbo diesel 4-cylinder engine paired with a 6-speed sports automatic transmission and all-wheel drive. Features include panoramic sunroof, partial leather interior, heated and ventilated front seats, heated rear seats, satellite navigation, reverse camera, front and rear parking sensors, blind spot monitoring, lane departure warning, adaptive cruise control, power tailgate, keyless entry, push-button start, dual-zone climate control, premium 10-speaker sound system, 19-inch alloy wheels and 5 star ANCAP safety rating. This Sorento has travelled 123,604km and is listed as drive away with roadworthy certificate, registration included, finance available and 12 month warranty included.",
  features: [
    "7 seats",
    "Panoramic sunroof",
    "Partial leather interior",
    "Heated front seats",
    "Ventilated front seats",
    "Heated rear seats",
    "Electric front seats",
    "Driver memory seat",
    "Electric lumbar support",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Blind spot monitoring",
    "Lane departure warning",
    "Adaptive cruise control",
    "Keyless entry",
    "Push-button start",
    "Power tailgate",
    "Dual-zone climate control",
    "Heated steering wheel",
    "10 speaker premium stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "iPod input",
    "MP3 decoder",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Digital instrument display",
    "Tyre pressure monitoring",
    "Automatic headlights",
    "HID headlights",
    "LED daytime running lights",
    "LED tail lights",
    "Front fog lights",
    "Rear fog lights",
    "Electric anti-glare mirror",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Roof rails",
    "Rear roof spoiler",
    "Cargo cover",
    "Cargo net",
    "Cargo tie down hooks",
    "ISOFIX child seat anchors",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "Selectable driving modes",
    "AWD",
    "Electric park brake",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2016-hyundai-tucson-highlander-awd",
  title: "2016 Hyundai Tucson Highlander Auto AWD MY17",
  price: 17000,
  kms: "119,260 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Ara Blue",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGTUCSON",
  imageLabel: "Hyundai Tucson",
  image: "assets/vehicles/Hyundai Tucson 2016/car_01.png",
  images: [
    "assets/vehicles/Hyundai Tucson 2016/car_01.png",
    "assets/vehicles/Hyundai Tucson 2016/car_02.png",
    "assets/vehicles/Hyundai Tucson 2016/car_03.png",
    "assets/vehicles/Hyundai Tucson 2016/car_04.png",
    "assets/vehicles/Hyundai Tucson 2016/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/hyundai-tucson-2016/oag-ad-25964134/",
  description: "2016 Hyundai Tucson Highlander Auto AWD MY17 finished in Ara Blue with black interior. A top-of-the-range family SUV offering strong turbo diesel performance, excellent fuel economy, premium comfort and all-wheel-drive confidence. Powered by a 2.0L turbo diesel 4-cylinder engine paired with a 6-speed sports automatic transmission and AWD. Features include panoramic glass roof, partial leather interior, heated front and rear seats, ventilated front seats, satellite navigation, reverse camera, front and rear parking sensors, blind spot monitoring, lane departure warning, smart cruise control, power tailgate, keyless entry, push-button start, dual-zone climate control, premium audio, Apple CarPlay, Android Auto, LED daytime running lights, rain-sensing wipers and 19-inch alloy wheels. This Tucson has travelled 119,260km and is listed as drive away with roadworthy certificate, registration included, finance available and 12 month warranty included.",
  features: [
    "Panoramic glass roof",
    "Partial leather interior",
    "Heated front seats",
    "Heated rear seats",
    "Ventilated front seats",
    "Electric front seats",
    "Electric lumbar support",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Rear cross traffic alert",
    "Blind spot monitoring",
    "Lane departure warning",
    "Forward collision warning",
    "AEB low speed",
    "Smart cruise control",
    "Keyless entry",
    "Push-button start",
    "Power tailgate",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Premium audio system",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "MP3 decoder",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Digital instrument display",
    "Tyre pressure monitoring",
    "Automatic headlights",
    "LED daytime running lights",
    "LED tail lights",
    "Front fog lights",
    "Rear fog lights",
    "Rain-sensing wipers",
    "Electric anti-glare mirror",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Roof rails",
    "Cargo cover",
    "Cargo net",
    "Cargo tie down hooks",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "AWD",
    "Electric park brake",
    "Hill holder",
    "Trailer sway control",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2018-ford-endura-st-line-awd",
  title: "2018 Ford Endura ST-Line CA Auto AWD MY19",
  price: 17000,
  kms: "146,778 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Blue",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGENDURASTLINE",
  imageLabel: "Ford Endura",
  image: "assets/vehicles/Ford Endura 2018/car_01.png",
  images: [
    "assets/vehicles/Ford Endura 2018/car_01.png",
    "assets/vehicles/Ford Endura 2018/car_02.png",
    "assets/vehicles/Ford Endura 2018/car_03.png",
    "assets/vehicles/Ford Endura 2018/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/ford-endura-2018/oag-ad-25964018/",
  description: "2018 Ford Endura ST-Line CA Auto AWD MY19 finished in stunning Blue. A stylish and practical family SUV offering sporty ST-Line styling, strong turbo diesel performance, excellent highway comfort and confident AWD capability. Powered by a 2.0L turbo diesel 4-cylinder engine paired with an 8-speed sports automatic transmission and all-wheel drive. Features include leather and suede sports seats, satellite navigation, Apple CarPlay, Android Auto, reverse camera, front and rear parking sensors, adaptive cruise control, lane keep assist, blind spot monitoring, autonomous emergency braking, electric tailgate, keyless entry, push-button start, dual-zone climate control, Bluetooth, rain-sensing wipers, automatic headlights, premium alloy wheels and ISOFIX child seat anchors. This Endura has travelled 146,778km and is listed with roadworthy certificate, registration included, workshop inspection, finance available, trade-ins welcome and 12 month warranty included.",
  features: [
    "ST-Line sports styling package",
    "Leather and suede sports seats",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Adaptive cruise control",
    "Lane keep assist",
    "Lane departure warning",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Keyless entry",
    "Push-button start",
    "Electric tailgate",
    "Dual-zone climate control",
    "Rear air conditioning",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Voice recognition",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Digital instrument display",
    "Automatic headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Roof rails",
    "Rear roof spoiler",
    "Cargo cover",
    "ISOFIX child seat anchors",
    "Premium alloy wheels",
    "AWD",
    "Electric park brake",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "Multiple airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2020-ford-ranger-xl-super-cab",
  title: "2020 Ford Ranger XL PX MkIII Auto 4x4 MY20.25 Super Cab",
  price: 20999,
  kms: "191,066 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "Ute",
  colour: "Arctic White",
  engine: "3.2L 5 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "DFGHSDKJD5555",
  imageLabel: "Ford Ranger",
  image: "assets/vehicles/Ford Ranger 2020/car_01.png",
  images: [
    "assets/vehicles/Ford Ranger 2020/car_01.png",
    "assets/vehicles/Ford Ranger 2020/car_02.png",
    "assets/vehicles/Ford Ranger 2020/car_03.png",
    "assets/vehicles/Ford Ranger 2020/car_04.png",
    "assets/vehicles/Ford Ranger 2020/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/ford-ranger-2020/oag-ad-26016064/",
  description: "2020 Ford Ranger XL PX MkIII Auto 4x4 MY20.25 Super Cab finished in Arctic White with black interior. A dependable work-ready ute built for trades, business use and everyday reliability. Powered by a 3.2L 5-cylinder turbo diesel engine paired with a 6-speed sports automatic transmission and dual-range 4x4 system. Features include Apple CarPlay, Android Auto, reverse camera, rear parking sensors, Bluetooth connectivity, cruise control, air conditioning, multi-function steering wheel, power windows, remote central locking, heavy duty vinyl flooring, automatic headlights, auto high beam, hill descent control, hill holder, trailer sway control, traction control and 5 star ANCAP safety rating. This Ranger has travelled 191,066km and is listed as plus on-roads with roadworthy certificate, workshop inspection, finance available, trade-ins welcome and 12 month premium warranty included.",
  features: [
    "Super Cab",
    "Cab Chassis",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "Reverse camera",
    "Rear parking sensors",
    "Forward collision warning",
    "AEB low speed",
    "Pedestrian avoidance braking",
    "Lane departure warning",
    "Lane keep assist",
    "Driver attention detection",
    "Cruise control",
    "Speed limiter",
    "Air conditioning",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "MP3 decoder",
    "Smart device app display",
    "Multi-function colour control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Road sign recognition",
    "Automatic headlights",
    "Auto high beam",
    "Halogen headlights",
    "Daytime running lights",
    "Power windows",
    "Electric mirrors",
    "Manual anti-glare mirror",
    "Remote central locking",
    "Engine immobiliser",
    "Cloth seats",
    "Heavy duty vinyl flooring",
    "Driver lumbar adjustment",
    "Cargo tie down hooks",
    "Mudflaps",
    "16-inch steel wheels",
    "Full size steel spare wheel",
    "4x4 dual range",
    "Hi-low speed transfer case",
    "Diff locks",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2011-audi-q5-tdi-quattro",
  title: "2011 Audi Q5 TDI Auto quattro MY12",
  price: 11510,
  kms: "112,458 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Ice Silver",
  engine: "3.0L V6 Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUDIQ5",
  imageLabel: "Audi Q5",
  image: "assets/vehicles/Audi Q5 2011/car_01.png",
  images: [
    "assets/vehicles/Audi Q5 2011/car_01.png",
    "assets/vehicles/Audi Q5 2011/car_02.png",
    "assets/vehicles/Audi Q5 2011/car_03.png",
    "assets/vehicles/Audi Q5 2011/car_04.png",
    "assets/vehicles/Audi Q5 2011/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/audi-q5-2011/oag-ad-26070462/",
  description: "2011 Audi Q5 TDI Auto quattro MY12 finished in Ice Silver. A premium European SUV offering strong V6 turbo diesel performance, Audi quattro all-wheel-drive confidence and excellent everyday comfort. Powered by a 3.0L turbo diesel 6-cylinder engine paired with a 7-speed automatic transmission. Features include full leather interior, electric front seats, satellite navigation, reverse camera, front and rear parking sensors, Bluetooth connectivity, cruise control, proximity keyless entry, push-button start, dual-zone climate control, automatic bi-xenon headlights, rain-sensing wipers, power tailgate, premium 10-speaker sound system, 18-inch alloy wheels, roof rails and 5 star ANCAP safety rating. This Audi Q5 has travelled 112,458km and is listed as drive away with roadworthy certificate, finance available and 12 month warranty included.",
  features: [
    "quattro all-wheel drive",
    "Full leather interior",
    "Electric front seats",
    "Driver electric lumbar support",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Proximity keyless entry",
    "Push-button start",
    "Cruise control",
    "Dual-zone climate control",
    "Ambient interior lighting",
    "10 speaker stereo",
    "Subwoofer",
    "Premium amplifier",
    "AUX input",
    "USB input",
    "iPod input",
    "CD player",
    "Multi-function control screen",
    "Colour display screen",
    "Multi-function steering wheel",
    "Sports steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Automatic bi-xenon headlights",
    "Electric headlight adjustment",
    "Headlight washers",
    "Front fog lights",
    "Rear fog lights",
    "Rain-sensing wipers",
    "Power windows",
    "Electric anti-glare mirror",
    "Electric mirrors",
    "Power tailgate",
    "Remote boot release",
    "Roof rails",
    "Rear roof spoiler",
    "Woodgrain interior trim",
    "Front centre armrest",
    "Split fold rear seats",
    "ISOFIX child seat anchors",
    "18-inch alloy wheels",
    "Electric park brake",
    "Hill descent control",
    "Electronic differential lock",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2016-jeep-cherokee-sport",
  title: "2016 Jeep Cherokee Sport KL Auto MY16",
  price: 11510,
  kms: "120,123 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Deep Cherry Red",
  engine: "2.4L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "IN070",
  imageLabel: "Jeep Cherokee",
  image: "assets/vehicles/Jeep Cherokee 2016/car_01.png",
  images: [
    "assets/vehicles/Jeep Cherokee 2016/car_01.png",
    "assets/vehicles/Jeep Cherokee 2016/car_02.png",
    "assets/vehicles/Jeep Cherokee 2016/car_03.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/jeep-cherokee-2016/oag-ad-26119955/",
  description: "2016 Jeep Cherokee Sport KL Auto MY16 finished in Deep Cherry Red with black interior. A spacious and comfortable family SUV offering smooth automatic driving, economical 2.4L petrol performance and practical everyday usability. Powered by a 2.4L MultiAir petrol 4-cylinder engine paired with a 9-speed sports automatic transmission. Features include full service history, Bluetooth, reverse camera, rear parking sensors, cruise control, central locking, air conditioning, voice recognition, multi-function control screen, 6 speaker stereo, AUX/USB input, LED daytime running lights, electric folding heated mirrors, electric park brake, 17-inch alloy wheels, traction control, stability control, hill holder and trailer sway control. This Jeep Cherokee has travelled 120,123km and is listed with roadworthy certificate, registration included, finance available, trade-ins welcome and 1-year mechanical warranty included.",
  features: [
    "Full service history",
    "Bluetooth",
    "Reverse camera",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Central locking",
    "Remote keyless entry",
    "Air conditioning",
    "Rear air conditioning",
    "Pollen filter",
    "Voice recognition",
    "Multi-function control screen",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Memory card reader",
    "MP3 decoder",
    "Multi-function steering wheel",
    "Trip computer",
    "Compass",
    "Tyre pressure monitoring",
    "Power windows",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "LED daytime running lights",
    "LED tail lights",
    "Rear fog lamps",
    "Rear wiper",
    "Cloth interior",
    "Split fold rear seats",
    "Cargo net",
    "Cargo tie down hooks",
    "17-inch alloy wheels",
    "Full size alloy spare wheel",
    "Electric park brake",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags"
  ]
},
{
  id: "2024-tesla-model-3-rear-wheel-drive",
  title: "2024 Tesla Model 3 Rear-Wheel Drive Auto MY24",
  price: 51096,
  kms: "50,216 km",
  transmission: "Automatic",
  fuel: "Electric",
  warranty: "Balance of Tesla factory warranty included",
  body: "Sedan",
  colour: "Pearl White",
  engine: "208kW Electric Motor",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGTESLAMD3",
  imageLabel: "Tesla Model 3",
  image: "assets/vehicles/Tesla Model 3 2024/car_01.png",
  images: [
    "assets/vehicles/Tesla Model 3 2024/car_01.png",
    "assets/vehicles/Tesla Model 3 2024/car_02.png",
    "assets/vehicles/Tesla Model 3 2024/car_03.png",
    "assets/vehicles/Tesla Model 3 2024/car_04.png",
    "assets/vehicles/Tesla Model 3 2024/car_05.png",
    "assets/vehicles/Tesla Model 3 2024/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/tesla-model-3-2024/oag-ad-26170195/",
  description: "2024 Tesla Model 3 MY24 Rear-Wheel Drive finished in Pearl White with black interior. A late-model fully electric sedan offering smooth performance, excellent efficiency, modern Tesla technology and a premium driving experience. Powered by a 208kW electric motor with single-speed reduction gear transmission and rear-wheel drive. Features include Autopilot, large 15.4-inch touchscreen display, vegan leather-look interior, heated front and rear seats, heated steering wheel, glass panoramic roof, wireless phone charging, satellite navigation, Bluetooth connectivity, adaptive cruise control, lane keep assist, blind spot monitoring, collision avoidance assist, front, side and rear cameras, LED matrix headlights, dual-zone climate control, over-the-air software updates, regenerative braking and fast DC charging capability. This Model 3 has travelled 50,216km and is listed with roadworthy certificate, registration, clear PPSR, workshop inspection, professional detailing and balance of Tesla factory warranty.",
  features: [
    "Full electric",
    "Rear wheel drive",
    "208kW electric motor",
    "Single speed reduction gear",
    "Autopilot",
    "15.4-inch touchscreen display",
    "Vegan leather-look interior",
    "Heated front seats",
    "Heated rear seats",
    "Heated steering wheel",
    "Ventilated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Glass panoramic roof",
    "Wireless phone charging",
    "Bluetooth",
    "GPS satellite navigation",
    "Digital radio",
    "9 speaker stereo",
    "Subwoofer",
    "USB input",
    "Smart device app control",
    "Remote connectivity via app",
    "Digital instrument display",
    "Front camera",
    "Rear camera",
    "Side cameras",
    "Reverse camera",
    "Front cross traffic alert",
    "Blind spot monitoring",
    "Lane departure warning",
    "Lane keep assist",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Pedestrian avoidance braking",
    "Driver attention detection",
    "Road sign recognition",
    "Adaptive cruise control",
    "Dual-zone climate control",
    "Remote climate start",
    "Ambient interior lighting",
    "Keyless start",
    "Key proximity entry",
    "Automatic LED headlights",
    "Auto high beam",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Power tailgate",
    "Split fold rear seats",
    "18-inch alloy wheels",
    "Regenerative braking",
    "Electric park brake",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "7 airbags",
    "5 star ANCAP safety rating",
    "513km WLTP estimated range",
    "62.5kWh battery capacity",
    "Fast DC charging capable"
  ]
},
{
  id: "2025-subaru-impreza-20s-g6",
  title: "2025 Subaru Impreza 2.0S G6 Auto AWD MY26",
  price: 32990,
  kms: "9,573 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "Balance of Subaru factory warranty included",
  body: "Hatch",
  colour: "Magnetite Grey",
  engine: "2.0L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGSUBARUIMPR",
  imageLabel: "Subaru Impreza",
  image: "assets/vehicles/Subaru Imprezza 2025/car_01.png",
  images: [
    "assets/vehicles/Subaru Imprezza 2025/car_01.png",
    "assets/vehicles/Subaru Imprezza 2025/car_02.png",
    "assets/vehicles/Subaru Imprezza 2025/car_03.png",
    "assets/vehicles/Subaru Imprezza 2025/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/subaru-impreza-2025/oag-ad-26169320/",
  description: "2025 Subaru Impreza 2.0S G6 Auto AWD MY26 finished in Magnetite Grey with black interior. A near-new top-of-the-range hatchback offering Subaru’s Symmetrical All-Wheel Drive, excellent safety technology, premium comfort and everyday practicality. Powered by a 2.0L Boxer petrol engine paired with an 8-speed Lineartronic automatic transmission and AWD. Features include Subaru EyeSight driver assist, adaptive cruise control, lane keep assist, blind spot monitoring, rear cross traffic alert, 360 degree surround view camera, front and rear parking sensors, leather appointed interior, heated front seats, electric driver’s seat with memory, sunroof, wireless Apple CarPlay, wireless Android Auto, wireless phone charging, satellite navigation, Harman Kardon premium sound system, dual-zone climate control, LED headlights and 18-inch alloy wheels. This Impreza has travelled only 9,573km and is listed as drive away with balance of Subaru factory warranty, roadworthy certificate, registration, clear PPSR, workshop inspection and professional detailing.",
  features: [
    "Symmetrical AWD",
    "Subaru EyeSight driver assist",
    "Adaptive cruise control",
    "Lane keep assist",
    "Lane departure warning",
    "Blind spot monitoring",
    "Rear cross traffic alert",
    "Front cross traffic alert",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Pedestrian avoidance braking",
    "Driver attention detection",
    "Road sign recognition",
    "360 degree surround view camera",
    "Front camera",
    "Reverse camera",
    "Side cameras",
    "Front parking sensors",
    "Rear parking sensors",
    "Sunroof",
    "Leather appointed interior",
    "Heated front seats",
    "Electric driver seat",
    "Driver memory seat",
    "Electric lumbar support",
    "Wireless Apple CarPlay",
    "Wireless Android Auto",
    "Wireless phone charging",
    "Bluetooth",
    "GPS satellite navigation",
    "Digital radio",
    "Harman Kardon premium sound system",
    "10 speaker stereo",
    "Premium amplifier",
    "USB input",
    "USB-C charging ports",
    "Large touchscreen infotainment system",
    "Dual-zone climate control",
    "Climate control with memory",
    "Smart key",
    "Push-button start",
    "Keyless entry",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Tyre pressure monitoring",
    "Automatic LED headlights",
    "Active cornering headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "LED fog lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirror",
    "Privacy glass",
    "Rear roof spoiler",
    "Cargo blind",
    "Cargo tie down hooks",
    "Split fold rear seats",
    "Sports pedals",
    "18-inch alloy wheels",
    "Space saver spare wheel",
    "Stop-start system",
    "Selectable driving modes",
    "Electric park brake",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "9 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2014-jeep-compass-north",
  title: "2014 Jeep Compass North MK Auto MY15",
  price: 10466,
  kms: "106,237 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Granite Crystal",
  engine: "2.0L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGJEEPCOMAPS",
  imageLabel: "Jeep Compass",
  image: "assets/vehicles/Jeep Compass 2014/car_01.png",
  images: [
    "assets/vehicles/Jeep Compass 2014/car_01.png",
    "assets/vehicles/Jeep Compass 2014/car_02.png",
    "assets/vehicles/Jeep Compass 2014/car_03.png",
    "assets/vehicles/Jeep Compass 2014/car_04.png",
    "assets/vehicles/Jeep Compass 2014/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/jeep-compass-2014/oag-ad-26137315/",
  description: "2014 Jeep Compass North MK Auto MY15 finished in Granite Crystal with black interior. A practical and affordable compact SUV offering low kilometres for its age, smooth automatic driving and comfortable everyday usability. Powered by a 2.0L petrol 4-cylinder engine paired with a CVT automatic transmission and front-wheel drive. Features include Bluetooth, reverse camera, satellite navigation, cruise control, central locking, air conditioning, voice recognition, multi-function colour screen, USB and AUX input, power windows, power mirrors, roof rails, fog lights, alloy wheels, split folding rear seats, ISOFIX child seat anchors, traction control and electronic stability control. This Jeep Compass has travelled 106,237km and is listed as drive away with roadworthy certificate, registration, workshop inspection, professional detailing, finance available, trade-ins welcome and 12 month premium mechanical warranty included.",
  features: [
    "Bluetooth",
    "Reverse camera",
    "GPS satellite navigation",
    "Cruise control",
    "Central locking",
    "Remote keyless entry",
    "Air conditioning",
    "Pollen filter",
    "Voice recognition",
    "Multi-function colour control screen",
    "4 speaker stereo",
    "AUX input",
    "USB input",
    "MP3 decoder",
    "CD player",
    "DVD player",
    "Inbuilt hard drive",
    "Multi-function steering wheel",
    "Trip computer",
    "Tyre pressure monitoring",
    "Power windows",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirror",
    "Front fog lights",
    "Rear fog lights",
    "Rear wiper",
    "Privacy glass",
    "Cloth interior",
    "Leather steering wheel",
    "Metallic interior trim",
    "Heated front seats",
    "Height adjustable driver seat",
    "Split fold rear seats",
    "Cargo cover",
    "Cargo tie down hooks",
    "ISOFIX child seat anchors",
    "Roof rails",
    "17-inch alloy wheels",
    "Full size steel spare wheel",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "Rollover stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "4 star ANCAP safety rating"
  ]
},
{
  id: "2018-holden-spark-ls",
  title: "2018 Holden Spark LS MP Auto MY18",
  price: 8990,
  kms: "138,548 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month premium warranty included",
  body: "Hatch",
  colour: "Absolute Red",
  engine: "1.4L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGHLDNSPARK",
  imageLabel: "Holden Spark",
  image: "assets/vehicles/Holden Spark 2018/car_01.png",
  images: [
    "assets/vehicles/Holden Spark 2018/car_01.png",
    "assets/vehicles/Holden Spark 2018/car_02.png",
    "assets/vehicles/Holden Spark 2018/car_03.png",
    "assets/vehicles/Holden Spark 2018/car_04.png",
    "assets/vehicles/Holden Spark 2018/car_05.png",
    "assets/vehicles/Holden Spark 2018/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/holden-spark-2018/oag-ad-26146691/",
  description: "2018 Holden Spark LS MP Auto MY18 finished in Absolute Red with black interior. A compact and economical 5-door hatchback offering easy city driving, low running costs and modern connectivity. Powered by a 1.4L petrol 4-cylinder engine paired with a CVT automatic transmission and front-wheel drive. Features include Apple CarPlay, Android Auto, reverse camera, Bluetooth hands-free and audio streaming, cruise control, air conditioning, power windows, power mirrors, remote central locking, USB and AUX input, multi-function steering wheel, touchscreen infotainment, split folding rear seats, ISOFIX child seat anchors, electronic stability control and 5 star ANCAP safety rating. This Spark has travelled 138,548km and is listed with roadworthy certificate, registration, workshop inspection, professional detailing, finance available, trade-ins welcome and 12 month premium mechanical warranty included.",
  features: [
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "Reverse camera",
    "Cruise control",
    "Air conditioning",
    "Touchscreen infotainment system",
    "Smart device app display",
    "USB input",
    "AUX input",
    "iPod input",
    "6 speaker stereo",
    "MP3 decoder",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Power windows",
    "Power mirrors",
    "Remote central locking",
    "Engine immobiliser",
    "Flip/fold out key",
    "Daytime running lights",
    "Rear wiper",
    "Variable intermittent wipers",
    "Cloth interior",
    "Height adjustable driver seat",
    "Split folding rear seats",
    "ISOFIX child seat anchors",
    "12V auxiliary socket",
    "Space saver spare wheel",
    "Front wheel drive",
    "CVT automatic transmission",
    "1.4L petrol engine",
    "5.5L/100km combined fuel economy",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2011-holden-captiva-7-cx",
  title: "2011 Holden Captiva 7 CX CG Auto AWD MY10",
  price: 5990,
  kms: "182,680 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Nitrate Silver",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHG3CAPTIV7ST",
  imageLabel: "Holden Captiva",
  image: "assets/vehicles/Holden Captiva 2011/car_01.png",
  images: [
    "assets/vehicles/Holden Captiva 2011/car_02.png",
    "assets/vehicles/Holden Captiva 2011/car_01.png",
    "assets/vehicles/Holden Captiva 2011/car_03.png",
    "assets/vehicles/Holden Captiva 2011/car_04.png",
    "assets/vehicles/Holden Captiva 2011/car_05.png"
    
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/holden-captiva-2011/oag-ad-26066798/",
  description: "2011 Holden Captiva 7 CX CG Auto AWD MY10 finished in Nitrate Silver. A practical and affordable 7-seat family SUV offering turbo diesel efficiency, all-wheel-drive capability and plenty of room for everyday family use. Powered by a 2.0L turbo diesel 4-cylinder engine paired with a 5-speed sports automatic transmission. Features include 7 seat configuration, leather interior, heated front seats, electric driver’s seat, satellite navigation, reverse camera, rear parking sensors, Bluetooth connectivity, cruise control, climate control, keyless entry, push-button start, power windows, roof rails, alloy wheels, hill descent control, traction control and electronic stability control. This Captiva has travelled 182,680km and is listed as drive away with roadworthy certificate, finance available and 12 month warranty included.",
  features: [
    "7 seats",
    "Leather interior",
    "Heated front seats",
    "Electric driver seat",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Climate control",
    "Pollen filter",
    "Keyless entry",
    "Push-button start",
    "6 speaker stereo",
    "AUX input",
    "MP3 decoder",
    "6 disc CD stacker",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Power windows",
    "Power tailgate",
    "Remote central locking",
    "Engine immobiliser",
    "Automatic headlights",
    "Front fog lights",
    "Rear wiper",
    "Electric mirrors",
    "Roof rails",
    "Split fold second row seats",
    "Flat folding third row seats",
    "Cargo storage compartment",
    "12V auxiliary sockets",
    "17-inch alloy wheels",
    "Space saver spare wheel",
    "AWD",
    "Hill descent control",
    "Rollover stability control",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "4 airbags",
    "4 star ANCAP safety rating",
    "1,700kg braked towing capacity"
  ]
},
{
  id: "2018-ford-ranger-xlt-px-mkiii",
  title: "2018 Ford Ranger XLT PX MkIII Auto 4x4 MY19 Double Cab",
  price: 30682,
  kms: "105,403 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "Ute",
  colour: "Frozen White",
  engine: "2.0L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "MPBUMFF60JX198636",
  imageLabel: "Ford Ranger",
  image: "assets/vehicles/Ford Ranger 2018/car_06.png",
  images: [
    "assets/vehicles/Ford Ranger 2018/car_06.png",
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/ford-ranger-2018/oag-ad-26015857/",
  description: "2018 Ford Ranger XLT PX MkIII Auto 4x4 MY19 Double Cab finished in Frozen White. A highly sought-after Aussie dual cab ute offering strong twin turbo diesel performance, 4x4 capability, excellent towing capacity and everyday practicality. Powered by a 2.0L twin turbo diesel 4-cylinder engine paired with a 10-speed sports automatic transmission and dual-range 4x4 system. Features include Apple CarPlay, Android Auto, satellite navigation, reverse camera, front and rear parking sensors, proximity keyless entry, push-button start, dual-zone climate control, cruise control, Bluetooth, digital radio, voice control, automatic headlights, rain-sensing wipers, sports bar, tow bar, heavy duty tub liner, side steps, alloy wheels and 5 star ANCAP safety rating. This Ranger has travelled 105,403km and is listed with roadworthy certificate, workshop inspection, finance available, trade-ins welcome and 12 month premium warranty included.",
  features: [
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Proximity keyless entry",
    "Push-button start",
    "Cruise control",
    "Speed limiter",
    "Dual-zone climate control",
    "Cooled centre console storage",
    "Digital radio",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "MP3 decoder",
    "CD player",
    "Voice recognition",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Digital instrument display",
    "Tyre pressure monitoring",
    "Automatic headlights",
    "HID headlights",
    "LED daytime running lights",
    "Front fog lights",
    "Rain-sensing wipers",
    "Electric anti-glare mirror",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Sports bar",
    "Side steps",
    "Rear step bumper",
    "Tow bar",
    "Heavy duty tub liner",
    "Cargo tie down hooks",
    "Mudflaps",
    "Alloy wheels",
    "ISOFIX child seat anchors",
    "4x4 dual range",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "Multiple airbags",
    "5 star ANCAP safety rating",
    "3.5 tonne braked towing capacity"
  ]
},
{
  id: "2015-nissan-qashqai-st",
  title: "2015 Nissan QASHQAI ST J11 Auto",
  price: 12550,
  kms: "151,335 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12–36 month extended warranty options available",
  body: "SUV",
  colour: "Ivory Pearl",
  engine: "2.0L 4 Cylinder Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOQASHQAI",
  imageLabel: "Nissan QASHQAI",
  image: "assets/vehicles/Nissan Qashqai 2015/car_15.png",
  images: [
    "assets/vehicles/Nissan Qashqai 2015/car_15.png",
    "assets/vehicles/Nissan Qashqai 2015/car_01.png",
    "assets/vehicles/Nissan Qashqai 2015/car_03.png",
    "assets/vehicles/Nissan Qashqai 2015/car_04.png",
    "assets/vehicles/Nissan Qashqai 2015/car_05.png",
    "assets/vehicles/Nissan Qashqai 2015/car_06.png",
    "assets/vehicles/Nissan Qashqai 2015/car_07.png",
    "assets/vehicles/Nissan Qashqai 2015/car_08.png",
    "assets/vehicles/Nissan Qashqai 2015/car_09.png",
    "assets/vehicles/Nissan Qashqai 2015/car_10.png",
    "assets/vehicles/Nissan Qashqai 2015/car_11.png",
    "assets/vehicles/Nissan Qashqai 2015/car_12.png",
    "assets/vehicles/Nissan Qashqai 2015/car_13.png",
    "assets/vehicles/Nissan Qashqai 2015/car_14.png",
    "assets/vehicles/Nissan Qashqai 2015/car_15.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/nissan-qashqai-2015/oag-ad-25806740/",
  description: "2015 Nissan QASHQAI ST J11 Auto finished in Ivory Pearl with black interior. A reliable, economical and practical 5-seat SUV, ideal for daily driving, first car buyers or small families. Powered by a 2.0L 4-cylinder petrol engine with automatic CVT transmission and front-wheel drive, offering smooth driving and excellent fuel economy of 6.9L/100km combined. This QASHQAI has travelled 151,335km and is listed as drive away with roadworthy certificate included, registration until January 2027 and 12–36 month extended warranty options available.",
  features: [
    "Reverse camera",
    "Bluetooth",
    "Cruise control",
    "Air conditioning",
    "Power windows",
    "Multi-function steering wheel",
    "USB/AUX input",
    "4 speaker stereo",
    "17-inch alloy wheels",
    "LED daytime running lights",
    "Remote central locking",
    "Electric mirrors",
    "Split fold rear seats",
    "Spacious 430L boot",
    "Excellent fuel economy",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Hill holder",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2014-range-rover-evoque-td4-pure-tech",
  title: "2014 Land Rover Range Rover Evoque TD4 Pure Tech Auto 4x4 MY15",
  price: 17777,
  kms: "154,239 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.2L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGLANDDISC5",
  imageLabel: "Range Rover Evoque",
  image: "assets/vehicles/Range Rover Evoque 2014/car_01.png",
  images: [
    "assets/vehicles/Range Rover Evoque 2014/car_05.png",
    "assets/vehicles/Range Rover Evoque 2014/car_01.png",
    "assets/vehicles/Range Rover Evoque 2014/car_02.png",
    "assets/vehicles/Range Rover Evoque 2014/car_03.png",
    "assets/vehicles/Range Rover Evoque 2014/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-range-rover-evoque-2014/oag-ad-25830599/",
  description: "2014 Land Rover Range Rover Evoque TD4 Pure Tech Auto 4x4 MY15 finished in Fuji White with black interior. A stylish compact luxury SUV offering strong diesel performance, premium comfort and confident 4x4 capability. Powered by a 2.2L turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission and constant 4x4 drive. Features include leather interior, satellite navigation, reverse camera, front and rear parking sensors, keyless entry, push-button start, dual-zone climate control, Bluetooth connectivity, Meridian sound system, cruise control, multi-function steering wheel, 18-inch alloy wheels, daytime running lights and all-terrain driving confidence. This Evoque has travelled 154,239km and is listed as drive away with 12 month warranty included.",
  features: [
    "Leather interior",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Keyless entry",
    "Push-button start",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Cruise control",
    "Meridian sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "MP3 decoder",
    "CD player",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "On-board computer",
    "Ambient lighting",
    "Power windows",
    "Electric heated mirrors",
    "Remote central locking",
    "Engine immobiliser",
    "Front fog lamps",
    "LED daytime running lights",
    "Rear roof spoiler",
    "Roof rails",
    "18-inch alloy wheels",
    "Space saver spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "4x4 constant drive",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "5 airbags",
    "4 star ANCAP safety rating"
  ]
},
{
  id: "2015-bmw-1-series-118i",
  title: "2015 BMW 1 Series 118i F20 Auto MY15",
  price: 14500,
  kms: "129,972 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month premium warranty included",
  body: "Hatch",
  colour: "Glacier Silver",
  engine: "1.6L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "SDGASDFG44444",
  imageLabel: "BMW 1 Series",
  image: "assets/vehicles/BMW 1 Series 2015/car_01.png",
  images: [
    "assets/vehicles/BMW 1 Series 2015/car_06.png",
    "assets/vehicles/BMW 1 Series 2015/car_01.png",
    "assets/vehicles/BMW 1 Series 2015/car_02.png",
    "assets/vehicles/BMW 1 Series 2015/car_03.png",
    "assets/vehicles/BMW 1 Series 2015/car_04.png",
    "assets/vehicles/BMW 1 Series 2015/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-1-series-2015/oag-ad-26016216/",
  description: "2015 BMW 1 Series 118i F20 Auto MY15 finished in Glacier Silver with black interior. A stylish and economical premium hatchback offering BMW driving dynamics, smooth automatic performance and practical everyday comfort. Powered by a 1.6L TwinPower turbo petrol 4-cylinder engine paired with an 8-speed automatic transmission. Features include satellite navigation, reverse camera, rear parking sensors, Bluetooth phone and audio streaming, dual-zone climate control, cruise control, push-button start, keyless entry, automatic headlights, rain-sensing wipers, alloy wheels, premium interior trim, drive mode select, ISOFIX child seat anchors and 5 star ANCAP safety rating. This BMW 118i has travelled 129,972km and is listed as drive away with roadworthy certificate, registration, workshop inspection, finance available and 12 month premium warranty included.",
  features: [
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Speed limiter",
    "Push-button start",
    "Keyless entry",
    "Dual-zone climate control",
    "Rear air conditioning",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "Inbuilt hard drive",
    "CD player",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "On-board computer",
    "Tyre pressure monitoring",
    "Automatic headlights",
    "Front fog lights",
    "Rain-sensing wipers",
    "Rear wiper",
    "Electric anti-glare mirror",
    "Electric heated mirrors",
    "Power windows",
    "Remote central locking",
    "Engine immobiliser",
    "Leather-look seats",
    "Premium interior trim",
    "Leather steering wheel",
    "Split fold rear seats",
    "Cargo net",
    "Cargo tie down hooks",
    "ISOFIX child seat anchors",
    "Alloy wheels",
    "Drive mode select",
    "Eco Pro mode",
    "Comfort mode",
    "Sport mode",
    "Rear wheel drive",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "ABS brakes",
    "Brake assist",
    "Multiple airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2017-land-rover-discovery-sport-td4-hse-white",
  title: "2017 Land Rover Discovery Sport TD4 132kW HSE Auto 4x4 MY18",
  price: 18690,
  kms: "93,780 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGLANDROVERDISWHITEL550",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Sport White 2017/car_01.png",
  images: [
    "assets/vehicles/Range Rover Sport White 2017/car_06.png",
    "assets/vehicles/Range Rover Sport White 2017/car_01.png",
    "assets/vehicles/Range Rover Sport White 2017/car_02.png",
    "assets/vehicles/Range Rover Sport White 2017/car_03.png",
    "assets/vehicles/Range Rover Sport White 2017/car_04.png",
    "assets/vehicles/Range Rover Sport White 2017/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2017/oag-ad-25819626/",
  description: "2017 Land Rover Discovery Sport TD4 132kW HSE L550 MY18 finished in Fuji White with black interior. A premium family SUV combining luxury comfort, strong turbo diesel performance and practical all-wheel drive capability. Powered by a 2.0L turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission and 4x4 constant drive. Features include leather interior, electric memory seats, panoramic glass roof, satellite navigation, reverse camera, front and rear parking sensors, power tailgate, keyless entry, push-button start, dual-zone climate control, cruise control, lane keep assist, autonomous emergency braking, Meridian premium sound system, LED daytime running lights, 19-inch alloy wheels and 5 star ANCAP safety rating. This Discovery Sport has travelled 93,780km and is listed as drive away with roadworthy certificate provided, finance available and 12 month warranty included.",
  features: [
    "Leather interior",
    "Electric memory seats",
    "Panoramic glass roof",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Lane departure warning",
    "Lane keep assist",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Cruise control",
    "Speed limiter",
    "Keyless entry",
    "Push-button start",
    "Power tailgate",
    "Dual-zone climate control",
    "Pollen filter",
    "Humidity sensor",
    "Meridian premium sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "Memory card reader",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Ambient interior lighting",
    "Footwell lamps",
    "Automatic headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "Front fog lamps",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric anti-glare mirror",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric mirrors with memory",
    "Power windows",
    "Split fold rear seats",
    "Sliding rear seat adjustment",
    "Cargo cover",
    "Cargo tie down hooks",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 constant drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2013-bmw-x1-sdrive18d",
  title: "2013 BMW X1 sDrive18d E84 LCI Auto MY14",
  price: 9999,
  kms: "115,260 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Alpine White",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOBMWX1",
  imageLabel: "BMW X1",
  image: "assets/vehicles/BMW X1 2013/car_03.png",
  images: [
    "assets/vehicles/BMW X1 2013/car_20.png",
    "assets/vehicles/BMW X1 2013/car_03.png",
    "assets/vehicles/BMW X1 2013/car_02.png",
    "assets/vehicles/BMW X1 2013/car_04.png",
    "assets/vehicles/BMW X1 2013/car_01.png",
    "assets/vehicles/BMW X1 2013/car_05.png",
    "assets/vehicles/BMW X1 2013/car_06.png",
    "assets/vehicles/BMW X1 2013/car_07.png",
    "assets/vehicles/BMW X1 2013/car_08.png",
    "assets/vehicles/BMW X1 2013/car_09.png",
    "assets/vehicles/BMW X1 2013/car_10.png",
    "assets/vehicles/BMW X1 2013/car_11.png",
    "assets/vehicles/BMW X1 2013/car_12.png",
    "assets/vehicles/BMW X1 2013/car_13.png",
    "assets/vehicles/BMW X1 2013/car_14.png",
    "assets/vehicles/BMW X1 2013/car_15.png",
    "assets/vehicles/BMW X1 2013/car_16.png",
    "assets/vehicles/BMW X1 2013/car_17.png",
    "assets/vehicles/BMW X1 2013/car_18.png",
    "assets/vehicles/BMW X1 2013/car_19.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x1-2013/oag-ad-25806679/",
  description: "2013 BMW X1 sDrive18d E84 LCI Auto MY14 finished in Alpine White with black interior. A great value luxury compact SUV offering BMW styling, excellent diesel economy and smooth automatic driving. Powered by a 2.0L turbo diesel 4-cylinder engine paired with an 8-speed sports automatic transmission and rear wheel drive. Features include sunroof, leather/suede interior, satellite navigation, Bluetooth, rear parking sensors, cruise control, dual-zone climate control, automatic headlights, rain-sensing wipers, push-button start, 17-inch alloy wheels, roof rails, traction control, electronic stability control and 5 star ANCAP safety rating. This BMW X1 has travelled 115,260km and is listed as drive away with roadworthy certificate, registration and 12 month warranty included.",
  features: [
    "Sunroof",
    "Leather/suede interior",
    "Bluetooth",
    "GPS satellite navigation",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Cruise control",
    "Speed limiter with brake function",
    "Dual-zone climate control",
    "Pollen filter",
    "Push-button start",
    "Voice recognition",
    "5 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "MP3 decoder",
    "CD player",
    "Multi-function colour control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "On-board computer",
    "Tyre pressure monitoring",
    "Automatic headlights",
    "Daytime running lights",
    "Front fog lights",
    "Rear fog lights",
    "Rain-sensing wipers",
    "Power windows",
    "Remote central locking",
    "Engine immobiliser",
    "Leather-look seats",
    "Leather steering wheel",
    "Metallic interior trim",
    "Split fold rear seats",
    "Cargo tie down hooks",
    "Roof rails",
    "17-inch alloy wheels",
    "Runflat tyres",
    "Stop-start system",
    "Rear wheel drive",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "6 airbags",
    "5 star ANCAP safety rating"
  ]
},
];

const services = [
  { title: "Paintless Dent Removal", text: "Remove minor dents while keeping the original paint finish where suitable." },
  { title: "Spray Painting", text: "Quality automotive paint refinishing for repaired panels and cosmetic restoration." },
  { title: "Panel Beating", text: "Dent, accident and body repair support to help your car look right again." },
  { title: "RWC Checks", text: "Roadworthy inspection support before selling, buying or re-registering a vehicle." },
  { title: "Auto Electrical Repairs", text: "Battery, electrical fault and vehicle system checks for modern vehicles." },
  { title: "Air Conditioning", text: "Car air conditioning inspection, repairs and gas refill support where required." },
  { title: "Mechanical Repairs", text: "General mechanical repairs and servicing for many makes and models." },
  { title: "Maintenance Services", text: "Regular maintenance checks to help keep your vehicle reliable and road-ready." },
  { title: "Car Body Repairs", text: "Scratch, dent and car body repair assistance for minor and major body damage." },
  { title: "European Auto Repairs", text: "Workshop support for European vehicles with experienced technicians." }
];

const reviews = [
  { name: "Hemant Khande", title: "Super quick service", text: "Got my car tyre puncture fixed. Super quick and reasonable price. I would recommend this shop." },
  { name: "Barbershop Convo", title: "Best in business", text: "Best in business, always supporting, and truthfully advising. Please go and visit the workshop!" },
  { name: "Lee Benson", title: "Good quality and prices", text: "I had my car body repair at KHG and I am so happy with the service, good quality and good prices." },
  { name: "Kanak Jagarlamudi", title: "Nice service and assistance", text: "Bought a car here, very nice service and assistance. Must check out if you want to buy a used car or car services." },
  { name: "Zale Ath", title: "Great value", text: "Great value and efficient service. Had brake pads front and rear replaced within 3 hours for a very reasonable price. Highly recommended!" },
  { name: "Sam", title: "Exceptional service", text: "Exceptional service, professional, efficient and super friendly. Very competitive with price and the workmanship is second to none." }
];
