const vehicles = [
{
  id: "2015-bmw-x5-xdrive30d-black",
  title: "2015 BMW X5 xDrive30d F15 Auto 4x4",
  price: 20888,
  kms: "160,605 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Azurite Black",
  engine: "3.0L 6 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGBMWF15X57SEAT",
  imageLabel: "BMW X5",
  image: "assets/vehicles/BMW X5 2015 Black/car_01.png",
  images: [
    "assets/vehicles/BMW X5 2015 Black/car_01.png",
    "assets/vehicles/BMW X5 2015 Black/car_02.png",
    "assets/vehicles/BMW X5 2015 Black/car_03.png",
    "assets/vehicles/BMW X5 2015 Black/car_04.png",
    "assets/vehicles/BMW X5 2015 Black/car_05.png",
    "assets/vehicles/BMW X5 2015 Black/car_06.png",
    "assets/vehicles/BMW X5 2015 Black/car_07.png",
    "assets/vehicles/BMW X5 2015 Black/car_08.png",
    "assets/vehicles/BMW X5 2015 Black/car_09.png",
    "assets/vehicles/BMW X5 2015 Black/car_10.png",
    "assets/vehicles/BMW X5 2015 Black/car_11.png",
    "assets/vehicles/BMW X5 2015 Black/car_12.png",
    "assets/vehicles/BMW X5 2015 Black/car_13.png",
    "assets/vehicles/BMW X5 2015 Black/car_14.png",
    "assets/vehicles/BMW X5 2015 Black/car_15.png",
    "assets/vehicles/BMW X5 2015 Black/car_16.png",
    "assets/vehicles/BMW X5 2015 Black/car_17.png",
    "assets/vehicles/BMW X5 2015 Black/car_18.png",
    "assets/vehicles/BMW X5 2015 Black/car_19.png",
    "assets/vehicles/BMW X5 2015 Black/car_20.png",
    "assets/vehicles/BMW X5 2015 Black/car_21.png",
    "assets/vehicles/BMW X5 2015 Black/car_22.png",
    "assets/vehicles/BMW X5 2015 Black/car_23.png",
    "assets/vehicles/BMW X5 2015 Black/car_24.png",
    "assets/vehicles/BMW X5 2015 Black/car_25.png",
    "assets/vehicles/BMW X5 2015 Black/car_26.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-x5-2015/oag-ad-25819559/",
  description: "2015 BMW X5 xDrive30d F15 Auto 4x4 finished in Azurite Black with black interior. A highly optioned luxury SUV offering powerful turbo diesel performance, premium comfort and strong practicality. Powered by a 3.0L 6-cylinder turbo diesel engine paired with an 8-speed sports automatic transmission and BMW xDrive all-wheel drive. This X5 has travelled 156,605km and is listed with roadworthy certificate provided, finance available and 12 month warranty included.",
  features: [
    "7 seat configuration",
    "Full leather interior",
    "Electric memory seats",
    "Panoramic sunroof",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "360 degree camera",
    "Adaptive cruise control",
    "Lane departure warning",
    "Blind spot monitoring",
    "Forward collision warning",
    "AEB low speed",
    "Dual-zone climate control",
    "Power tailgate",
    "Keyless entry",
    "Push-button start",
    "Premium sound system",
    "9 speaker stereo",
    "DVD player",
    "USB input",
    "AUX input",
    "iPod input",
    "Head-up display",
    "Voice recognition",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Heated mirrors",
    "19-inch alloy wheels",
    "Roof rails",
    "Selectable driving modes",
    "Stop-start system",
    "Sports steering wheel",
    "Hill descent control",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Tyre pressure monitoring",
    "6 airbags"
  ]
},
{
  id: "2016-bmw-2-series-228i-sport-line",
  title: "2016 BMW 2 Series 228i Sport Line F22 Auto",
  price: 19000,
  kms: "94,880 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month warranty included",
  body: "Coupe",
  colour: "White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGAUTOBMW2",
  imageLabel: "BMW 2 Series",
  image: "assets/vehicles/BMW 2 Series 2016/car_01.png",
  images: [
    "assets/vehicles/BMW 2 Series 2016/car_02.png",
    "assets/vehicles/BMW 2 Series 2016/car_01.png",
    "assets/vehicles/BMW 2 Series 2016/car_03.png",
    "assets/vehicles/BMW 2 Series 2016/car_04.png",
    "assets/vehicles/BMW 2 Series 2016/car_05.png",
    "assets/vehicles/BMW 2 Series 2016/car_06.png",
    "assets/vehicles/BMW 2 Series 2016/car_07.png",
    "assets/vehicles/BMW 2 Series 2016/car_08.png",
    "assets/vehicles/BMW 2 Series 2016/car_09.png",
    "assets/vehicles/BMW 2 Series 2016/car_10.png",
    "assets/vehicles/BMW 2 Series 2016/car_11.png",
    "assets/vehicles/BMW 2 Series 2016/car_12.png",
    "assets/vehicles/BMW 2 Series 2016/car_13.png",
    "assets/vehicles/BMW 2 Series 2016/car_14.png",
    "assets/vehicles/BMW 2 Series 2016/car_15.png",
    "assets/vehicles/BMW 2 Series 2016/car_16.png",
    "assets/vehicles/BMW 2 Series 2016/car_17.png",
    "assets/vehicles/BMW 2 Series 2016/car_18.png",
    "assets/vehicles/BMW 2 Series 2016/car_19.png",
    "assets/vehicles/BMW 2 Series 2016/car_20.png",
    "assets/vehicles/BMW 2 Series 2016/car_21.png",
    "assets/vehicles/BMW 2 Series 2016/car_22.png",
    "assets/vehicles/BMW 2 Series 2016/car_23.png",
    "assets/vehicles/BMW 2 Series 2016/car_24.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/bmw-2-series-2016/oag-ad-25897808/",
  description: "2016 BMW 2 Series 228i Sport Line F22 Auto finished in white with a stylish coupe body. A sporty and refined 2-door BMW coupe offering strong turbo petrol performance, premium comfort and everyday usability. Powered by a 2.0L turbo intercooled 4-cylinder petrol engine paired with an 8-speed sports automatic transmission and rear-wheel drive. This BMW 228i has travelled 94,880km and is listed with 12 month warranty included.",
  features: [
    "Bluetooth",
    "Reverse camera",
    "GPS satellite navigation",
    "Front parking sensors",
    "Rear parking sensors",
    "Cruise control",
    "Automatic headlights",
    "Bi-xenon headlights",
    "LED daytime running lights",
    "Front fog lamps",
    "Rear fog lamps",
    "Dual-zone climate control",
    "Leather interior",
    "Sports front seats",
    "Push-button start",
    "Digital radio",
    "USB input",
    "AUX input",
    "iPod input",
    "MP3 decoder",
    "Inbuilt harddisk drive",
    "6 speaker stereo",
    "Multi-function control screen",
    "Smart device app display/control",
    "Paddle shifters",
    "Selectable driving modes",
    "Sports steering wheel",
    "Electric power steering",
    "Rain-sensing wipers",
    "Heated washer jets",
    "Electric heated mirrors",
    "Trip computer",
    "On-board computer",
    "Tyre pressure monitoring",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Rear wheel drive",
    "Stop-start system",
    "ABS brakes",
    "Brake assist",
    "Traction control",
    "Electronic stability control",
    "Corner braking control",
    "6 airbags"
  ]
},
{
  id: "2017-mercedes-benz-gla220d",
  title: "2017 Mercedes-Benz GLA-Class GLA220 d Auto",
  price: 17000,
  kms: "125,349 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Cirrus White",
  engine: "2.1L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "ADFGADSF",
  imageLabel: "Mercedes-Benz GLA",
  image: "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
  images: [
    "assets/vehicles/Mercedes Benz GLA 2017/car_01.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_02.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_03.png",
    "assets/vehicles/Mercedes Benz GLA 2017/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/mercedes-benz-gla-class-2017/oag-ad-26016339/",
  description: "2017 Mercedes-Benz GLA220 d X156 Auto finished in Cirrus White with black interior. A premium compact luxury SUV offering strong turbo diesel efficiency, smooth automatic driving and a refined Mercedes-Benz cabin. Powered by a 2.1L turbo diesel 4-cylinder engine paired with a 7-speed sports automatic dual clutch transmission. Features include Apple CarPlay, Android Auto, satellite navigation, reverse camera, front and rear parking sensors, blind spot monitoring, autonomous emergency braking, dual-zone climate control, leather-look interior, heated front seats, electric front seats, keyless start, power tailgate, automatic bi-xenon headlights, rain-sensing wipers, Bluetooth, digital radio, 18-inch alloy wheels and excellent fuel economy. This GLA220 d has travelled 125,349km and is listed with roadworthy certificate, registration, finance available and 12 month premium warranty included.",
  features: [
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Automated parking assistance",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Driver attention detection",
    "Cruise control",
    "Speed limiter",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Leather-look interior",
    "Heated front seats",
    "Electric front seats",
    "Electric lumbar support",
    "Keyless start",
    "Push-button start",
    "Power tailgate",
    "Digital radio",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "iPod input",
    "CD player",
    "Automatic bi-xenon headlights",
    "LED daytime running lights",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Tyre pressure monitoring",
    "Roof rails",
    "18-inch alloy wheels",
    "Runflat tyres",
    "Electric park brake",
    "Hill holder",
    "Stop-start system",
    "Selectable driving modes",
    "Front wheel drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "9 airbags"
  ]
},
{
  id: "2017-land-rover-discovery-sport-sd4-hse",
  title: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18",
  price: 15999,
  kms: "93,780 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Twin Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "JHGSDF2225",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Sport 2017/car_01.png",
  images: [
    "assets/vehicles/Range Rover Sport 2017/car_01.png",
    "assets/vehicles/Range Rover Sport 2017/car_02.png",
    "assets/vehicles/Range Rover Sport 2017/car_03.png",
    "assets/vehicles/Range Rover Sport 2017/car_04.png",
    "assets/vehicles/Range Rover Sport 2017/car_05.png",
    "assets/vehicles/Range Rover Sport 2017/car_06.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2017/oag-ad-26015662/",
  description: "2017 Land Rover Discovery Sport SD4 HSE Auto 4x4 MY18 finished in Fuji White with black interior. A premium family SUV combining luxury comfort, strong twin turbo diesel performance and intelligent all-wheel drive capability. Powered by a 2.0L twin turbo diesel 4-cylinder engine paired with a 9-speed sports automatic transmission. Features include full leather interior, panoramic glass sunroof, satellite navigation, Apple CarPlay, Android Auto, reverse camera, front and rear parking sensors, electric tailgate, heated front seats, electric front seats with memory, keyless entry, push-button start, dual-zone climate control, Meridian premium sound system, lane keep assist, blind spot monitoring, autonomous emergency braking, adaptive cruise control and 19-inch alloy wheels. This Discovery Sport has travelled only 86,408km and is listed as drive away with roadworthy certificate, registration included, finance available and 12 month premium warranty included.",
  features: [
    "Full leather interior",
    "Panoramic glass sunroof",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Lane departure warning",
    "Lane keep assist",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Adaptive cruise control",
    "Keyless entry",
    "Push-button start",
    "Electric tailgate",
    "Heated front seats",
    "Ventilated front seats",
    "Electric front seats",
    "Driver memory seat",
    "Passenger memory seat",
    "Electric lumbar support",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Meridian premium sound system",
    "11 speaker stereo",
    "Subwoofer",
    "AUX input",
    "USB input",
    "Memory card reader",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Trip computer",
    "Speed limiter",
    "Automatic headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Ambient interior lighting",
    "Split fold rear seats",
    "Sliding rear seat adjustment",
    "Cargo cover",
    "ISOFIX child seat anchors",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 on demand",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2021-land-rover-discovery-sport-p200-r-dynamic-s",
  title: "2021 Land Rover Discovery Sport P200 R-Dynamic S Auto 4x4 MY21",
  price: 27140,
  kms: "106,147 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month premium warranty included",
  body: "SUV",
  colour: "Fuji White",
  engine: "2.0L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "HGJF22254",
  imageLabel: "Land Rover Discovery Sport",
  image: "assets/vehicles/Range Rover Discovery 2021/car_01.png",
  images: [
    "assets/vehicles/Range Rover Discovery 2021/car_01.png",
    "assets/vehicles/Range Rover Discovery 2021/car_02.png",
    "assets/vehicles/Range Rover Discovery 2021/car_03.png",
    "assets/vehicles/Range Rover Discovery 2021/car_04.png",
    "assets/vehicles/Range Rover Discovery 2021/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/land-rover-discovery-sport-2021/oag-ad-26015523/",
  description: "2021 Land Rover Discovery Sport P200 R-Dynamic S Auto 4x4 MY21 finished in Fuji White with black interior. A late-model premium SUV with modern R-Dynamic styling, 7-seat practicality, strong turbo petrol performance and advanced safety technology. Powered by a 2.0L turbo petrol 4-cylinder engine paired with a 9-speed sports automatic transmission and constant 4x4 drive. Features include Apple CarPlay, Android Auto, satellite navigation, 360 degree camera, front and rear parking sensors, blind spot assist, lane keep assist, autonomous emergency braking, adaptive cruise control, keyless start, electric tailgate, dual-zone climate control, leather-look interior, electric front seats, digital driver display, LED headlights, rain-sensing wipers, 18-inch alloy wheels and 5 star ANCAP safety rating. This Discovery Sport has travelled 106,147km and is listed with roadworthy certificate, registration included, finance available and 12 month premium warranty included.",
  features: [
    "7 seats",
    "R-Dynamic sports styling package",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "360 degree camera",
    "Reverse camera",
    "Front camera",
    "Side cameras",
    "Front parking sensors",
    "Rear parking sensors",
    "Rear cross traffic alert",
    "Blind spot assist",
    "Lane departure warning",
    "Lane keep assist",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Adaptive cruise control",
    "Driver fatigue warning",
    "Road sign recognition",
    "Keyless start",
    "Push-button start",
    "Electric tailgate",
    "Dual-zone climate control",
    "Pollen filter",
    "Leather-look interior",
    "Partial leather seats",
    "Electric front seats",
    "Electric lumbar support",
    "Digital driver display",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Wireless hotspot",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Speed limiter",
    "Ambient lighting",
    "Footwell lamps",
    "Automatic LED headlights",
    "LED daytime running lights",
    "LED tail lights",
    "Rear fog lamps",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Electric anti-glare mirrors",
    "Power windows",
    "ISOFIX child seat anchors",
    "Cargo cover",
    "Cargo tie down hooks",
    "18-inch alloy wheels",
    "Space saver spare wheel",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Rollover stability control",
    "Selectable driving modes",
    "4x4 constant drive",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2018-ford-endura-st-line-awd",
  title: "2018 Ford Endura ST-Line CA Auto AWD MY19",
  price: 16720,
  kms: "146,859 km",
  transmission: "Automatic",
  fuel: "Diesel",
  warranty: "12 month warranty included",
  body: "SUV",
  colour: "Blue",
  engine: "2.0L 4 Cylinder Turbo Diesel",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGENDURASTLINE",
  imageLabel: "Ford Endura",
  image: "assets/vehicles/Ford Endura 2018/car_01.png",
  images: [
    "assets/vehicles/Ford Endura 2018/car_01.png",
    "assets/vehicles/Ford Endura 2018/car_02.png",
    "assets/vehicles/Ford Endura 2018/car_03.png",
    "assets/vehicles/Ford Endura 2018/car_04.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/ford-endura-2018/oag-ad-25964018/",
  description: "2018 Ford Endura ST-Line CA Auto AWD MY19 finished in stunning Blue. A stylish and practical family SUV offering sporty ST-Line styling, strong turbo diesel performance, excellent highway comfort and confident AWD capability. Powered by a 2.0L turbo diesel 4-cylinder engine paired with an 8-speed sports automatic transmission and all-wheel drive. Features include leather and suede sports seats, satellite navigation, Apple CarPlay, Android Auto, reverse camera, front and rear parking sensors, adaptive cruise control, lane keep assist, blind spot monitoring, autonomous emergency braking, electric tailgate, keyless entry, push-button start, dual-zone climate control, Bluetooth, rain-sensing wipers, automatic headlights, premium alloy wheels and ISOFIX child seat anchors. This Endura has travelled 146,778km and is listed with roadworthy certificate, registration included, workshop inspection, finance available, trade-ins welcome and 12 month warranty included.",
  features: [
    "ST-Line sports styling package",
    "Leather and suede sports seats",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Adaptive cruise control",
    "Lane keep assist",
    "Lane departure warning",
    "Blind spot monitoring",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Keyless entry",
    "Push-button start",
    "Electric tailgate",
    "Dual-zone climate control",
    "Rear air conditioning",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Voice recognition",
    "Multi-function control screen",
    "Multi-function steering wheel",
    "Trip computer",
    "Digital instrument display",
    "Automatic headlights",
    "LED daytime running lights",
    "Rain-sensing wipers",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Roof rails",
    "Rear roof spoiler",
    "Cargo cover",
    "ISOFIX child seat anchors",
    "Premium alloy wheels",
    "AWD",
    "Electric park brake",
    "Hill holder",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "Multiple airbags",
    "5 star ANCAP safety rating"
  ]
},
{
  id: "2021-hyundai-tucson-elite-n-line-awd",
  title: "2021 Hyundai Tucson Elite N Line Auto AWD MY22",
  price: 26990,
  kms: "90,883 km",
  transmission: "Automatic",
  fuel: "Petrol",
  warranty: "12 month extended warranty included",
  body: "SUV",
  colour: "Available on request",
  engine: "1.6L 4 Cylinder Turbo Petrol",
  rego: "Available on request",
  vin: "Available on request",
  stockNo: "KHGHYUBDAIN",
  imageLabel: "Hyundai Tucson",
  image: "assets/vehicles/Hyundai Tucson 2021/car_01.png",
  images: [
    "assets/vehicles/Hyundai Tucson 2021/car_01.png",
    "assets/vehicles/Hyundai Tucson 2021/car_02.png",
    "assets/vehicles/Hyundai Tucson 2021/car_03.png",
    "assets/vehicles/Hyundai Tucson 2021/car_04.png",
    "assets/vehicles/Hyundai Tucson 2021/car_05.png"
  ],
  carsalesUrl: "https://www.carsales.com.au/cars/details/hyundai-tucson-2021/oag-ad-26259173/",
  description: "2021 Hyundai Tucson Elite N Line Auto AWD MY22. A sharp, sporty and highly equipped family SUV combining Hyundai’s N Line styling package with the practicality, comfort and safety technology expected from a modern Tucson. Powered by a 1.6L turbocharged petrol 4-cylinder engine paired with a 7-speed dual-clutch automatic transmission and all-wheel drive. Features include Apple CarPlay, Android Auto, satellite navigation, reverse camera, front and rear parking sensors, blind spot assist, lane keep assist, autonomous emergency braking, adaptive cruise control, smart key with push-button start, dual-zone climate control, wireless charging, digital radio, N Line sports seats, N Line interior styling, LED daytime running lights, privacy glass, 19-inch alloy wheels and 5 star ANCAP safety rating. This Tucson has travelled 90,883km and is listed with finance options available, trade-ins welcome and 12 month extended warranty included.",
  features: [
    "N Line sports styling package",
    "N Line interior",
    "N Line sports seats",
    "Apple CarPlay",
    "Android Auto",
    "Bluetooth",
    "GPS satellite navigation",
    "Wireless phone charging",
    "Digital radio",
    "6 speaker stereo",
    "AUX input",
    "USB input",
    "Smart device app display/control",
    "Reverse camera",
    "Front parking sensors",
    "Rear parking sensors",
    "Parking assistance graphical display",
    "Blind spot assist",
    "Lane departure warning",
    "Lane keep assist",
    "Forward collision warning",
    "Autonomous emergency braking",
    "Pedestrian avoidance braking",
    "Rear cross traffic alert",
    "Front cross traffic alert",
    "Driver attention detection",
    "Road sign recognition",
    "Adaptive cruise control",
    "Speed limiter",
    "Smart key",
    "Push-button start",
    "Key proximity entry",
    "Dual-zone climate control",
    "Rear air conditioning",
    "Pollen filter",
    "Partial leather seats",
    "Alcantara seat trim",
    "Heated front seats",
    "Electric driver seat",
    "Electric lumbar support",
    "Digital instrument display",
    "Trip computer",
    "Tyre pressure monitoring",
    "Multi-function steering wheel",
    "Paddle shifters",
    "Automatic headlights",
    "Auto high beam",
    "LED daytime running lights",
    "LED tail lights",
    "Rain-sensing wipers",
    "Rear wiper",
    "Electric folding mirrors",
    "Electric heated mirrors",
    "Privacy glass",
    "Roof rails",
    "Rear roof spoiler",
    "Cargo cover",
    "Cargo net",
    "Cargo tie down hooks",
    "Split fold rear seats",
    "ISOFIX child seat anchors",
    "19-inch alloy wheels",
    "Full size alloy spare wheel",
    "AWD",
    "Selectable driving modes",
    "Electric park brake",
    "Hill descent control",
    "Hill holder",
    "Trailer sway control",
    "Traction control",
    "Electronic stability control",
    "ABS brakes",
    "Brake assist",
    "Electronic brake force distribution",
    "7 airbags",
    "5 star ANCAP safety rating",
    "7.2L/100km combined fuel economy"
  ]
},
];

const services = [
  { title: "Paintless Dent Removal", text: "Remove minor dents while keeping the original paint finish where suitable." },
  { title: "Spray Painting", text: "Quality automotive paint refinishing for repaired panels and cosmetic restoration." },
  { title: "Panel Beating", text: "Dent, accident and body repair support to help your car look right again." },
  { title: "RWC Checks", text: "Roadworthy inspection support before selling, buying or re-registering a vehicle." },
  { title: "Auto Electrical Repairs", text: "Battery, electrical fault and vehicle system checks for modern vehicles." },
  { title: "Air Conditioning", text: "Car air conditioning inspection, repairs and gas refill support where required." },
  { title: "Mechanical Repairs", text: "General mechanical repairs and servicing for many makes and models." },
  { title: "Maintenance Services", text: "Regular maintenance checks to help keep your vehicle reliable and road-ready." },
  { title: "Car Body Repairs", text: "Scratch, dent and car body repair assistance for minor and major body damage." },
  { title: "European Auto Repairs", text: "Workshop support for European vehicles with experienced technicians." }
];

const reviews = [
  { name: "Hemant Khande", title: "Super quick service", text: "Got my car tyre puncture fixed. Super quick and reasonable price. I would recommend this shop." },
  { name: "Barbershop Convo", title: "Best in business", text: "Best in business, always supporting, and truthfully advising. Please go and visit the workshop!" },
  { name: "Lee Benson", title: "Good quality and prices", text: "I had my car body repair at KHG and I am so happy with the service, good quality and good prices." },
  { name: "Kanak Jagarlamudi", title: "Nice service and assistance", text: "Bought a car here, very nice service and assistance. Must check out if you want to buy a used car or car services." },
  { name: "Zale Ath", title: "Great value", text: "Great value and efficient service. Had brake pads front and rear replaced within 3 hours for a very reasonable price. Highly recommended!" },
  { name: "Sam", title: "Exceptional service", text: "Exceptional service, professional, efficient and super friendly. Very competitive with price and the workmanship is second to none." }
];
